apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "og-kafka-mm.fullname" . }}
  labels:
    app: {{ template "og-kafka-mm.name" . }}
    chart: {{ template "og-kafka-mm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "og-kafka-mm.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - interval: 15s
      port: prometheus-jmx
